apiVersion: v1
kind: ServiceAccount
metadata:
  name: kaniko-sa
  namespace: ci-cd
  annotations:
    # ARN from Terraform output (arn:aws:iam::802617578034:role/KanikoECRPushRole-homelab-eks)
    # This securely links the Service Account to the AWS IAM Role
    eks.amazonaws.com/role-arn: "arn:aws:iam::802617578034:role/KanikoECRPushRole-homelab-eks"