apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-demoapp-values
  namespace: default
data:
  values.yaml: |
    replicaCount: 2
    image:
      repository: 802617578034.dkr.ecr.eu-west-1.amazonaws.com/homelab-eks
      pullPolicy: IfNotPresent
      tag: 682d3bb4928a9d3cf5f61de9d9f420d0e5a718de
    service:
      type: ClusterIP
      port: 3000
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    serviceAccount:
      create: true
      name: ""
    httpRoute:
      enabled: false
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80
