apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nodejs-app
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/eks/flux-system/nodejs-app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
