apiVersion: v1
kind: Service
metadata:
  name: nodejs-demoapp-service
  namespace: ci-cd
spec:
  type: NodePort
  selector:
    app: nodejs-demoapp
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
