pipeline {
    environment {
        IMAGE_FULL_URI = '802617578034.dkr.ecr.eu-west-1.amazonaws.com/homelab-eks:latest'
        AWS_REGION = 'eu-west-1'
    }

    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
metadata:
  name: docker-agent
  namespace: ci-cd
spec:
  serviceAccountName: kaniko-sa  # normal Jenkins SA
  containers:
  - name: docker
    image: docker:24-dind
    securityContext:
      privileged: true             # needed for DinD
    command:
      - dockerd-entrypoint.sh
    args:
      - --host=tcp://0.0.0.0:2375 --host=unix:///var/run/docker.sock
    tty: true
"""
            defaultContainer 'docker'
        }
    }

    stages {
        stage('Build and Push Image') {
            steps {
                container('docker') {
                    sh '''
                    # Install AWS CLI
                    apk add --no-cache python3 py3-pip
                    pip3 install awscli --upgrade

                    # Authenticate Docker to ECR
                    aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 802617578034.dkr.ecr.eu-west-1.amazonaws.com

                    # Build the Docker image
                    docker build -t homelab-eks:latest ${WORKSPACE}/app-code/nodejs-demoapp/build

                    # Tag and push to ECR
                    docker tag homelab-eks:latest $IMAGE_FULL_URI
                    docker push $IMAGE_FULL_URI
                    '''
                }
            }
        }
    }
}
